/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AOption: typeof import('@arco-design/web-vue')['Option']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    BasicHeader: typeof import('./../views/common/layout/components/basic-header.vue')['default']
    BasicLeftSidebar: typeof import('./../views/common/layout/components/basic-left-sidebar.vue')['default']
    BasicRightSidebar: typeof import('./../views/common/layout/components/basic-right-sidebar.vue')['default']
    ClockButton: typeof import('./../views/home/components/clock-button.vue')['default']
    ClockIn: typeof import('./../views/home/components/clockIn.vue')['default']
    ClockInfo: typeof import('./../views/home/components/clock-info.vue')['default']
    InfoEdition: typeof import('./../views/home/components/info-edition.vue')['default']
    Information: typeof import('./../views/home/components/information.vue')['default']
    LineChart: typeof import('./../views/home/components/line-chart.vue')['default']
    LoginBackground: typeof import('./../views/login/components/login-background.vue')['default']
    LoginForm: typeof import('./../views/login/components/login-form.vue')['default']
    LoginSlider: typeof import('./../views/login/components/login-slider.vue')['default']
    OutsideLinks: typeof import('./../views/home/components/outside-links.vue')['default']
    RankList: typeof import('./../views/attendance/components/rank-list.vue')['default']
    RegisterForm: typeof import('./../views/login/components/register-form.vue')['default']
    RightSidebar: typeof import('./../views/home/components/right-sidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoList: typeof import('./../views/home/components/todo-list.vue')['default']
  }
}
